package maintenance

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	domainmedia "family-media-server/internal/domain/media"
)

var ErrUnsafeGeneratedDataPath = errors.New("unsafe generated data path")

type Result struct {
	ClearedDirectories int
}

type Service struct {
	repository    domainmedia.GeneratedDataRepository
	mediaRoot     string
	indexDBPath   string
	generatedDirs []string
}

func NewService(
	repository domainmedia.GeneratedDataRepository,
	mediaRoot string,
	indexDBPath string,
	generatedDirs ...string,
) *Service {
	return &Service{
		repository:    repository,
		mediaRoot:     mediaRoot,
		indexDBPath:   indexDBPath,
		generatedDirs: generatedDirs,
	}
}

// Clear removes only data generated by this service. The SQLite file remains
// open and reusable; original media and configuration files are never touched.
func (s *Service) Clear(ctx context.Context) (Result, error) {
	var result Result
	for _, directory := range s.generatedDirs {
		if strings.TrimSpace(directory) == "" {
			continue
		}
		if err := s.clearDirectory(ctx, directory); err != nil {
			return result, err
		}
		result.ClearedDirectories++
	}
	if err := s.repository.ClearGeneratedData(ctx); err != nil {
		return result, err
	}
	return result, nil
}

func (s *Service) clearDirectory(ctx context.Context, directory string) error {
	target, err := filepath.Abs(directory)
	if err != nil {
		return fmt.Errorf("resolve generated data directory: %w", err)
	}
	if err := s.validateTarget(target); err != nil {
		return err
	}

	info, err := os.Lstat(target)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect generated data directory: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%w: %s is not a regular directory", ErrUnsafeGeneratedDataPath, target)
	}
	resolvedTarget, err := filepath.EvalSymlinks(target)
	if err != nil {
		return fmt.Errorf("resolve generated data symlinks: %w", err)
	}
	if err := s.validateTarget(resolvedTarget); err != nil {
		return err
	}

	entries, err := os.ReadDir(target)
	if err != nil {
		return fmt.Errorf("read generated data directory: %w", err)
	}
	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := os.RemoveAll(filepath.Join(target, entry.Name())); err != nil {
			return fmt.Errorf("remove generated data: %w", err)
		}
	}
	return nil
}

func (s *Service) validateTarget(target string) error {
	resolvedTarget, err := resolvePath(target)
	if err != nil {
		return fmt.Errorf("resolve generated data path: %w", err)
	}
	target = resolvedTarget
	root := filepath.Clean(string(filepath.Separator))
	if target == root {
		return fmt.Errorf("%w: refusing filesystem root", ErrUnsafeGeneratedDataPath)
	}

	mediaRoot, err := resolvePath(s.mediaRoot)
	if err != nil {
		return fmt.Errorf("resolve media root: %w", err)
	}
	if pathsOverlap(target, mediaRoot) {
		return fmt.Errorf("%w: generated directory overlaps media root", ErrUnsafeGeneratedDataPath)
	}

	indexPath, err := resolvePath(s.indexDBPath)
	if err != nil {
		return fmt.Errorf("resolve index path: %w", err)
	}
	if target == indexPath || pathContains(target, indexPath) {
		return fmt.Errorf("%w: generated directory contains media index", ErrUnsafeGeneratedDataPath)
	}
	return nil
}

// resolvePath resolves symbolic links in the existing part of a path while
// preserving any not-yet-created suffix.
func resolvePath(value string) (string, error) {
	absolute, err := filepath.Abs(value)
	if err != nil {
		return "", err
	}
	current := absolute
	missing := make([]string, 0)
	for {
		resolved, err := filepath.EvalSymlinks(current)
		if err == nil {
			for index := len(missing) - 1; index >= 0; index-- {
				resolved = filepath.Join(resolved, missing[index])
			}
			return filepath.Clean(resolved), nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return filepath.Clean(absolute), nil
		}
		missing = append(missing, filepath.Base(current))
		current = parent
	}
}

func pathsOverlap(left string, right string) bool {
	return left == right || pathContains(left, right) || pathContains(right, left)
}

func pathContains(parent string, child string) bool {
	relative, err := filepath.Rel(parent, child)
	return err == nil && relative != "." && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator))
}
